server:
  port: 8185
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/clinicdb
    username: root


#  config:
#   import: optional:configserver:http://localhost:8888/

  application:
    name: clinic-service
    
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
      
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
      
management:
   endpoints:
       web:
         exposure:
            include:
            - prometheus
            - health
logging:
  file:
    name: clinic-service.log
